Vagrant.configure("2") do |config|
  config.vm.define "win2019" do | w19 |
    w19.vm.box = "StefanScherer/windows_2019"
    w19.vm.network "private_network", ip: "172.19.0.15"
    w19.vm.provider "virtualvox" do |vb|
      vb.memory = 4000
      vb.cpus = 4
    end
  end
  config.vm.define "win10" do | w10 |
    w10.vm.box = "scotch/box"
    w10.vm.network "private_network", ip: "172.19.0.15"
    w10.vm.provider "virtualvox" do |vb|
      vb.memory = 2000
      vb.cpus = 2
    end
  end
end 
