Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "server-vgs"
  config.vm.synced_folder "compartida", "/mnt", create: true
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Ubuntu Server"
    vb.memory = 2000
    vb.cpus = 2
  end
end
