Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.hostname = "ubuntu22"
  config.vm.provider "virtualbox" do |vb|
   vb.name ="Ubuntu22scripter"
   vb.memory = 2000
   vb.cpus = 2
  end
 end